version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb_new
